// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq3LqOZKSSf4cbfVrTFTjWA35h4YF6jaA',
    appId: '1:966988385090:web:59f80150cefbda2d6dd6db',
    messagingSenderId: '966988385090',
    projectId: 'news-tren',
    authDomain: 'news-tren.firebaseapp.com',
    storageBucket: 'news-tren.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2hmINEXMZ9kN2WedAR_e2MIKt413-fhU',
    appId: '1:966988385090:android:17cd0788041ec52f6dd6db',
    messagingSenderId: '966988385090',
    projectId: 'news-tren',
    storageBucket: 'news-tren.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7m1qxqOyM4D5H5B-s51190D7-gh5oSd0',
    appId: '1:966988385090:ios:8111890f7733db3f6dd6db',
    messagingSenderId: '966988385090',
    projectId: 'news-tren',
    storageBucket: 'news-tren.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7m1qxqOyM4D5H5B-s51190D7-gh5oSd0',
    appId: '1:966988385090:ios:8111890f7733db3f6dd6db',
    messagingSenderId: '966988385090',
    projectId: 'news-tren',
    storageBucket: 'news-tren.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq3LqOZKSSf4cbfVrTFTjWA35h4YF6jaA',
    appId: '1:966988385090:web:1aea13b1b0a400c46dd6db',
    messagingSenderId: '966988385090',
    projectId: 'news-tren',
    authDomain: 'news-tren.firebaseapp.com',
    storageBucket: 'news-tren.appspot.com',
  );

}